name: Build

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: Install Dependencies
        run: npm ci

      - name: Build App
        run: npm run build
